name: Publish packages

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        description: 'Package to publish'
        default: 'eslint-config-react'
        options:
          - eslint-config-react
          - prettier-config-react
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [eslint-config-react, prettier-config-react]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          scope: '@aittorai'

      - name: Configure .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@aittorai:registry=https://registry.npmjs.org" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Version bump
        if: github.event_name == 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
        run: |
          cd packages/${{ matrix.package }}
          npm version prepatch --preid=$(git rev-parse --short HEAD) --no-git-tag-version

      - name: Publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/${{ matrix.package }}
          FLAGS=""
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            FLAGS="--tag latest"
          fi
          pnpm publish --access public --no-git-checks $FLAGS