name: Publish package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        description: 'Package to publish'
        default: 'eslint-config-react'
        options:
          - eslint-config-react
          - prettier-config-react
  push:
    tags:
      - 'eslint-config-react@v*.*.*'
      - 'prettier-config-react@v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    strategy:
      matrix:
        registry:
          - url: npmjs.org
            token_secret: NPM_TOKEN
          - url: npm.pkg.github.com
            token_secret: GH_PAT
        package:
          - eslint-config-react
          - prettier-config-react
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: https://registry.${{ matrix.registry.url }}
          scope: '@aittorai'

      - name: Configure .npmrc
        run: |
          echo "//registry.${{ matrix.registry.url }}/:_authToken=${{ secrets[matrix.registry.token_secret] }}" > ~/.npmrc
          echo "@aittorai:registry=https://registry.${{ matrix.registry.url }}" >> ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Debug information
        run: |
          ls -la packages/${{ matrix.package }}
          cat packages/${{ matrix.package }}/package.json

      - name: Change directory and publish package
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token_secret] }}
        run: pnpm publish --access public --no-git-checks